configuration Example
{
    param
    (
        [parameter()]
        [string]
        $NodeName = 'localhost'
    )

    Import-DscResource -ModuleName PowerStig

    Node $NodeName
    {
        WindowsServer BaseLine
        {
            OsVersion   = '2012R2'
            OsRole      = 'MS'
            Exception   = @{
                'V-205733'= @{
                    'Identity'='Guests'
                }
                'V-205672'= @{
                    'Identity'='Guests'
                }
                'V-205673'= @{
                    'Identity'='Guests'
                }
                'V-205675'= @{
                    'Identity'='Guests'
                }
            }
            OrgSettings = @{
                'V-205910' = @{OptionValue = 'xGuest'}
                'V-205717' = @{Value = '2'}
            }
        }
    }
}

Example