---
- name: Install Required Software on Windows
  hosts: windows
  tasks:

    - name: Create temporary directory
      win_file:
        path: C:\temp
        state: directory

# Install Python 3 on Windows
    - name: Download Python installer
      win_get_url:
        url: https://www.python.org/ftp/python/3.9.12/python-3.9.12-amd64.exe
        dest: C:\temp\python-3.9.12-amd64.exe

    - name: Install Python
      win_command: C:\temp\python-3.9.12-amd64.exe /quiet InstallAllUsers=1 PrependPath=1
      args:
        chdir: C:\temp

    - name: Verify Python installation
      win_command: python --version
      register: python_version

    - name: Show Python version
      debug:
        msg: "Python version installed: {{ python_version.stdout }}"
        
# Install Chocolatey and Run Windows Update
    - name: Install Chocolatey
      win_chocolatey:
        name: chocolatey
        state: present

    - name: Install all security, critical, and rollup updates without a scheduled task
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
      become: true
      become_method: runas
      become_user: SYSTEM

# Install ADK and PE Add-ons on Windows
    - name: Download ADK installer
      win_get_url:
        url: https://go.microsoft.com/fwlink/?linkid=2271337
        dest: C:\temp\ADKSetup.exe

    - name: Download Windows PE Add-ons installer
      win_get_url:
        url: https://go.microsoft.com/fwlink/?linkid=2271338
        dest: C:\temp\WinPE_Addons_amd64.exe

    - name: Install ADK
      win_command: C:\temp\ADKSetup.exe /quiet
      args:
        chdir: C:\temp

    - name: Install Windows PE Add-ons
      win_command: C:\temp\WinPE_Addons_amd64.exe /quiet
      args:
        chdir: C:\temp

# Install PowerSTIG

    - name: Ensure NuGet provider is installed
      win_psmodule:
        name: PowerShellGet
        state: present

    - name: Install NuGet provider if not already installed
      ansible.windows.win_powershell:
        script: |
          Install-PackageProvider -Name NuGet -Force

    - name: Set PowerShell Execution Policy
      ansible.windows.win_powershell:
        script: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser -Force

    - name: Install PowerSTIG PowerShell Module
      ansible.windows.win_powershell:
        script: |
          Install-Module -Name PowerSTIG -Force -Scope CurrentUser