---
- name: Configure WinRM and Network Settings on Windows
  hosts: windows
  tasks:

    # - name: Set basic WinRM settings
    #   ansible.windows.win_powershell:
    #     script: |
    #       winrm quickconfig -q

    # - name: Get the name of the public profile
    #   ansible.windows.win_powershell:
    #     script: |
    #       $profile = Get-NetConnectionProfile
    #   register: net_profile

    # - name: Show public profile
    #   debug:
    #     msg: "Public profile: {{ net_profile }}"

    # - name: Update the InterfaceAlias parameter with the name of the profile from above
    #   ansible.windows.win_powershell:
    #     script: |
    #       Set-NetConnectionProfile -InterfaceAlias '{{ net_profile.output }}' -NetworkCategory Private

    - name: Update the WSMAN MaxEnvelopeSizekb
      ansible.windows.win_powershell:
        script: |
          Set-Item -Path WSMan:\localhost\MaxEnvelopeSizekb -Value 8192

    - name: Restart WinRM
      ansible.windows.win_powershell:
        script: |
          Restart-Service WinRM